### ISSUE TITLE
Projekt končan 

### ISSUE THREAD

**Issue by LampicJ15** [LampicJ15/APPR-2017#3]
Projekt zaključen
Zadnji komit: c81765e0fc1135e3df0ef5b3bffd943594c0a769

**Comment by jaanos** [comment]
V redu, poročilo prevede, tako da bom dodal povezavo na repozitorij za zagovore. Če se še nisi, se lahko s profesorjem domeniš za termin zagovora. Če boš še kaj spreminjal, mi javi, da posodobim povezavo.

Svetoval bi sicer, da nekoliko povišaš Shiny aplikacijo v poročilu (povečaj parameter `height`), da v nobenem zavihku ne bo viden drsnik. V grafih imaš na osi y napisano, da gre za število, a so vrednosti večinoma manjše od 1 - namesto z milijon podatke raje deli s 1000, v oznaki osi y pa zapiši, da gre za tisoče.
